name: 'Algolia Docsearch Indexer'
description: 'Update an Algolia Docsearch index'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  algolia_application_id:
    description: 'Algolia docsearch APPLICATION_ID'
    required: true
  algolia_api_key:
    description: 'Algolia docsearch API_KEY'
    required: true
  algolia_config_file:
    description: 'Algolia config file path to docsearch'
    required: true
    default: algolia.config.json
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.algolia_application_id }}
    - ${{ inputs.algolia_api_key }}
    - ${{ inputs.algolia_config_file }}
